package cfg

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Config holds all notification bridge settings.
type Config struct {
	AndroidIP    string
	SSHUser      string
	SSHPort      string
	DefaultTitle string
	Sound        bool
	Priority     string
	MaxRetries   int
	RetryDelay   int
}

// Default returns a Config with sensible defaults.
func Default() *Config {
	return &Config{
		AndroidIP:    "100.115.83.120",
		SSHUser:      "root",
		SSHPort:      "8022",
		DefaultTitle: "Mac Remote",
		Sound:        true,
		Priority:     "high",
		MaxRetries:   2,
		RetryDelay:   3,
	}
}

// Path returns the config file path, respecting NOTIFYBRIDGE_CONF env.
func Path() (string, error) {
	if env := os.Getenv("NOTIFYBRIDGE_CONF"); env != "" {
		return env, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("home directory: %w", err)
	}
	return filepath.Join(home, ".notifybridge.conf"), nil
}

// Load reads and parses the config file (backwards-compatible with bash format).
func Load() (*Config, error) {
	path, err := Path()
	if err != nil {
		return nil, err
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config %s: %w", path, err)
	}

	c := Default()
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		key, value, ok := parseKV(line)
		if !ok {
			continue
		}

		switch key {
		case "ANDROID_IP":
			c.AndroidIP = value
		case "SSH_USER":
			c.SSHUser = value
		case "SSH_PORT":
			c.SSHPort = value
		case "DEFAULT_TITLE":
			c.DefaultTitle = value
		case "SOUND":
			c.Sound = value != "false"
		case "PRIORITY":
			c.Priority = value
		case "MAX_RETRIES":
			if n, err := strconv.Atoi(value); err == nil {
				c.MaxRetries = n
			}
		case "RETRY_DELAY":
			if n, err := strconv.Atoi(value); err == nil {
				c.RetryDelay = n
			}
		}
	}

	return c, scanner.Err()
}

// Write saves the config to the given path.
func Write(path string, c *Config) error {
	content := fmt.Sprintf(`# NotifyBridge Configuration
# Auto-generated by notifybridge setup

# Tailscale IP of the Android device
ANDROID_IP=%q

# SSH user on Termux
SSH_USER=%q

# SSH port (Termux sshd default)
SSH_PORT=%q

# Default notification title
DEFAULT_TITLE=%q

# Sound on notification
SOUND=%v

# Notification priority
PRIORITY=%q

# Max retry attempts
MAX_RETRIES=%d

# Retry delay in seconds
RETRY_DELAY=%d
`, c.AndroidIP, c.SSHUser, c.SSHPort, c.DefaultTitle, c.Sound, c.Priority, c.MaxRetries, c.RetryDelay)

	return os.WriteFile(path, []byte(content), 0644)
}

func parseKV(line string) (string, string, bool) {
	idx := strings.Index(line, "=")
	if idx < 0 {
		return "", "", false
	}
	key := strings.TrimSpace(line[:idx])
	value := strings.TrimSpace(line[idx+1:])
	value = strings.Trim(value, "\"")
	return key, value, true
}
